# .travis.yml
# This file should be at the root of your project
# dist: xenial
language: ruby
cache: bundler # caching bundler gem packages will speed up build
before_script: 
  - gem install bundler
  - bundle update
  - chmod +x ./script/cibuild # or do this locally and commit
# the `install` step will run `bundle install` by default.
install: gem install jekyll
script: 
  - ./script/cibuild
  # - ./setup
  # - bundle exec rake test
  - bundle exec jekyll algolia
rvm:
 - 2.7.3
 - 3.0

    # branch whitelist, only for GitHub Pages
branches:
  only:
    - master
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - gh-pages     # test the gh-pages branch
    # - /pages-(.*)/ # test every branch which starts with "pages-"