# Welcome to Jekyll!
#
# You can find config options at: https://jekyllrb.com/docs/configuration/options/
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

title: "IT-Journey"
# theme: "minima"
markdown: kramdown
author: bamr87
# minima:
#   date_format: "%b %-d, %Y"
#   skin: dark
header_pages:
  - README.md
  - about.md
  - portfolio.md
  - blog.md
  - cheat-sheets.md
  - contact.md
  - /docs/structure/
include:
  - _docs/
  - _cheats/
plugins:
  - jekyll-include-cache
port: 4001
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

theme_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

collections:
  docs:
    output: true
  cheatsheet:
    output: true

# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  # _posts
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      toc: true
  # _docs
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "single"
      share: true
      toc: true
      toc_sticky: true
      sidebar:
        - nav: docs
  # _cheats
  - scope:
      path: "_cheats"
      type: "cheatsheet"
    values:
      layout: "single"
      share: true
      toc: true
      toc_sticky: true
      sidebar:
        - nav: cheat

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Denver # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


