# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# You can find config options at: https://jekyllrb.com/docs/configuration/options/
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# theme                  : "zer0-mistakes-jekyll"
# remote_theme           : "bamr87/zer0-mistakes"
theme_skin               : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings

title                    : IT-Journey
subtitle                 : "zer0 to her0"
subtitle_url             : "127.0.0.1"
masthead_title           : # override the default title
title_separator          : "|" # Appears in the web browser tab name
locale                   : "en-US"
name                     : &name "Amr"
email                    : bamr4287@gmail.com
description              : &description >- # this means to ignore newlines until "url:"
  Scrolls and spells of IT magic.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url                      : "https://lifehacker.dev" # the base hostname & protocol for your site, e.g. http://example.com
baseurl                  : "" # the subpath of your site, e.g. /blog
repository               : "bamr87/it-journey" # GitHub username/repo-name
local_repo               : "it-journey"
home_dir_pc              : &home-win 'C:\Users\amrab\'
home_dir_mac             : &home-mac '/Users/amr/'
local_git_pc             : [ *home-win, 'github\' ]
local_git_mac            : [ *home-mac, 'GitHub/' ]
teaser                   : /assets/images/teaser_default-500x300.png # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : /assets/images/gravatar-small.png # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
breadcrumbs              : true # true, false (default)
words_per_minute         : 200
port                     : 4002 # Jekyll Serve Dev port
dg_port                  : "4001" # Doppelganger site

# Identity

author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/gravatar-small.png"
  bio              : "IT nerd trying to be an IT hero"
  location         : "Denver, CO"
  links:
    - label: "BASH Consulting"
      icon: "fas fa-fw fa-link"
      url: "https://bashconsultants.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bamr87"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bamr87"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/bamr42"

twitter_username         : "bamr87"
github_username          : "bamr87"
# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-algolia
  # - jekyll-postcss
  # - jekyll-redirect-from
  
# Conversion
markdown: kramdown
highlighter: rouge
# lsi: false
# excerpt_separator: "\n\n"
# incremental: false

# Markdown Processing https://jekyllrb.com/docs/configuration/markdown/
kramdown: # https://kramdown.gettalong.org/options.html
  input: GFM
  header_offset: 0
  # hard_wrap: false
  # auto_ids: true
  # footnote_nr: 1
  # entity_output: as_char
  toc_levels: 1..6
  # smart_quotes: lsquo,rsquo,ldquo,rdquo
  # enable_coderay: false




# Collections: https://jekyllrb.com/docs/collections/
  # Permalinks: https://jekyllrb.com/docs/permalinks/

collections:
  docs:
    output: true
    permalink: /:collection/:path/
  notes:
    output: true
    permalink: /:collection/:path/
  quickstart:
    output: true
    permalink: /:collection/:path/
  about:
    output: true
    permalink: /:collection/:path/
  hobbies:
    output: true
    permalink: /:collection/:path/


# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/

defaults:
  # ALL
  - scope:
      path: ""
    values:
      layout: default
      show_date: true
      author_profile: false
      read_time: true
      comments: # true
      share: true
      related: true
      toc: true
      toc_sticky: true
      sidebar:
        nav: main
  # _posts
  - scope:
      path: _posts
    values:
      layout: default
      show_date: true
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      toc: true
      toc_sticky: true
      sidebar:
        nav: main
    permalink: /:categories/:title/
  # _notes
  - scope:
      path: "_notes"
      type: notes
    values:
      layout: default
      share: true
      toc: true
      author_profile: false
      toc_sticky: true
      sidebar:
        nav: notes
  # _quickstart
  - scope:
      path: "_quickstart"
      type: quickstart
    values:
      layout: default
      share: true
      toc: true
      author_profile: false
      toc_sticky: true
      sidebar:
        nav: quickstart
      permalink: /:categories/:title/
  # _about
  - scope:
      path: "_about"
      type: about
    values:
      layout: default
      share: true
      toc: true
      author_profile: false
      toc_sticky: true
      sidebar:
        nav: about
      permalink: /:categories/:title/
  # _hobbies
  - scope:
      path: "_hobbies"
      type: hobbies
    values:
      layout: default
      share: true
      toc: true
      author_profile: false
      toc_sticky: true
      sidebar:
        nav: hobbies
      permalink: /:categories/:title/

permalink: /:categories/:title/



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  

# Footer Links Settings

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bamr87"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bamr87"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/bamr42"

powered_by:
  - name: "Jekyll"
    url: "https://jekyllrb.com/"
  - name: "Bootstrap"
    url: "https://getbootstrap.com/"
  - name: "Algolia"
    url: "https://algolia.com/"
  - name: "JQuery"
    url: "https://jquery.com/"


algolia:
  application_id: '99CKJ6KQ3Z'
  search_only_api_key: '03a0c530bc2ff9acfde23485092602f3'
  index_name: dev_lifehacker

exclude: [vendor]

atom_feed:
path                   : # blank (default) uses feed.xml